### ISSUE TITLE
GI Parameters Serial Attributes

### ISSUE THREAD

**Issue by unitedbuilt** [Acumatica/Acumatica-LotSerialNbrAttribute-2023R1-ONWARD#4]
I am rebuilding a GI that showed availability of serialized items and their attributes. I was able to rebuild the GI to show the desired results grid with serialized attributes. However, if I try to use INItemLotSerialInfo attributes as a parameter/condition, it says it cannot find the field. Any idea why the field can be found for the results grid, but not for a parameter? Example, INItemLotSerialInfo.SERIES_Attributes

Being able to use attributes as parameters within the GI was a huge convenience - if anyone has an idea of how to accomplish this with the new changes any assistance is appreciated. I will continue to see if I can figure it out.

**Comment by unitedbuilt** [comment]
For reference, here is the error message when trying to use INItemLotSerialInfo.MODEL_Attributes

Trace
Error: A field with the name INItemLotSerialInfo.SERIES_Attributes cannot be found.
   at PX.Data.Description.GI.PXDesignedQueryProvider.FillTableAndDataField(PXParameter par, PXQueryDescription descr, String fieldName)
   at PX.Data.Description.GI.PXDesignedQueryProvider.CollectParameters(PXQueryDescription descr)
   at PX.Data.Description.GI.PXDesignedQueryProvider.FillDescription(PXQueryDescription descr)
   at PX.Data.Description.GI.PXQueryDescription.Create(IGenericQueryProvider prov)
   at PX.Data.PXGenericInqGrph.get_BaseQueryDescription()
   at PX.Data.PXGenericInqGrph.CollectDescriptionFields()
   at PX.Data.PXGenericInqGrph.PrepareCaches(GIDescription def, Dictionary`2 parameters)
   at PX.Data.PXGenericInqGrph.PrepareCaches(String id, String name, Dictionary`2 parameters, Boolean fetchSchema)
   at PX.Web.UI.PXGenericDataSource.InstantiateDataGraph(Type type)
   at PX.Web.UI.PXBaseDataSource.CreateDataGraphAsSingleton(Type type)
   at PX.Web.UI.PXBaseDataSource.CreateDataGraph(Type type)
   at PX.Web.UI.PXBaseDataSource.get_DataGraph()
   at PX.Web.UI.PXGrid.<>c.<RenderToolsRow>b__1115_0(PXDataSource ds)
   at PX.Common.Tools.With[TInput,TResult](TInput o, Func`2 evaluator)
   at PX.Web.UI.PXGrid.RenderToolsRow(Boolean top)
   at PX.Web.UI.PXGrid.CreateChildControls(IEnumerable dataSource, Boolean dataBinding)
   at System.Web.UI.WebControls.CompositeDataBoundControl.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.WebControls.CompositeDataBoundControl.get_Controls()
   at PX.Web.UI.PXSmartPanel.CollectInnerControls(ControlCollection controls, Boolean load, Boolean collectUpdatable)
   at PX.Web.UI.PXSmartPanel.CollectInnerControls(Boolean load)
   at PX.Web.UI.PXSmartPanel.SetBindingState(Boolean load)
   at PX.Web.UI.PXSmartPanel.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by DhirenChhapgar** [comment]
This issue is resolved in today's released package.
