### ISSUE TITLE
PPV (Purchase Price Variance) - Allocation Mode Inventory Account

### ISSUE THREAD

**Issue by unitedbuilt** [Acumatica/Acumatica-LotSerialNbrAttribute-2023R1-ONWARD#7]
When inventory is received at a lower cost than it is billed, we have Acumatica setup to issue an inventory adjustment add the variance as a landed cost. Recently, a Serialized item was received at one cost and the bill ended up being less. So it created an inventory adjustment to adjusted the landed cost of the Serialized item.

When trying to release the inventory adjustment we receive this error:

`Trace
`GetItemExtension failed.
PX.Data.PXException: GetItemExtension failed.
   at PX.Data.PXCacheEx.GetExtension[TExtension](IBqlTable item)
   at PX.LotSerialNbrAttribute.Ext.INReleaseProcessPXLotSerialExt.UpdateItemLotSerial(INTran tran, INTranSplit split, InventoryItem item, INLotSerClass lsclass, UpdateItemLotSerialBase BaseInvoke) in C:\Work Acumatica\Acumatica_Stash\SourceCode\Acumatica_Customization\_Common\2023R2\Acumatica-LotSerialNbrAttribute\PX.LotSertialNbrAttribute.Ext\PX.LotSerialNbrAttribute.Ext\IN\INReleaseProcessPXLotSerialExt.cs:line 22
   at Wrapper.PX.Objects.IN.InventoryRelease.Cst_INReleaseProcess.UpdateItemLotSerialGeneratedWrapper(INReleaseProcess g, INTran , INTranSplit , InventoryItem , INLotSerClass )
   at PX.Objects.IN.InventoryRelease.INReleaseProcess.ReleaseDocProc(JournalEntry je, INRegister doc, Boolean releaseFromHold)
   at PX.Objects.IN.InventoryRelease.INReleaseProcess.ReleaseDocProcR(JournalEntry je, INRegister doc, Boolean releaseFromHold)
   at PX.Objects.IN.INDocumentRelease.ReleaseDoc(List`1 list, Boolean isMassProcess, Boolean releaseFromHold, ActionFlow processFlow)
   at PX.Objects.IN.INDocumentRelease.ReleaseDoc(List`1 list, Boolean isMassProcess, Boolean releaseFromHold, ActionFlow processFlow)
   at PX.Objects.IN.INRegisterEntryBase.<>c__DisplayClass24_0.<Release>b__0()
   at PX.Concurrency.CancellationIgnorantExtensions.RunWithCancellationViaThreadAbort(Action method, CancellationToken cancellationToken)
   at PX.Concurrency.CancellationIgnorantExtensions.<>c__DisplayClass1_0.<ToCancellationViaThreadAbort>b__0(CancellationToken cancellationToken)
   at PX.Concurrency.Internal.PXLongOperationPars.PopAndRunDelegate(CancellationToken cancellationToken)
   at PX.Concurrency.Internal.RuntimeLongOperationManager.PerformOperation(PXLongOperationPars p)

![screenshot-watertrucks acumatica com-2024 02 06-12_07_36](https://github.com/Acumatica/Acumatica-LotSerialNbrAttribute-2023R1-ONWARD/assets/64986301/d5e7eb79-a48c-4751-b545-44265ef01d64)
![screenshot-watertrucks acumatica com-2024 02 06-12_08_05](https://github.com/Acumatica/Acumatica-LotSerialNbrAttribute-2023R1-ONWARD/assets/64986301/a05f5ad6-5fc2-41c7-bd59-8925bb897b33)
![screenshot-watertrucks acumatica com-2024 02 06-12_09_26](https://github.com/Acumatica/Acumatica-LotSerialNbrAttribute-2023R1-ONWARD/assets/64986301/dab04423-29dc-48ab-be23-da5d756d9dcf)

**Comment by unitedbuilt** [comment]
@DhirenChhapgar we recently upgraded to 2023R2 and I noticed there is a new package for that release. I will publish the updated package and try again.
